sudo: required

language: c

services:
  - docker

before_install:
  - docker info
  - docker build --no-cache -t izonder/janny .

script:
  - docker run -it --rm izonder/janny java -version

after_success:
  - curl -X POST https://registry.hub.docker.com/u/izonder/janny/trigger/$DOCKER_TRIGGER_TOKEN/
